### ISSUE TITLE
Pontoon friendly file structure

### ISSUE THREAD

**Issue by mathjazz** [birajkarmakar/Bengali-India-bn-IN-Fuel-Terminology#1]
For Pontoon to be able to properly detect templates and locales, some changes are needed to the file and folder structur in your repository. Each locale (including templates) has to be in a separate folder.

Example:

```
templates/
    fuel-cloud-bn.pot
    fuel-mobile-bn.pot
    fuel-web-bn.pot
bn-IN/
    fuel-cloud-bn.po
    fuel-mobile-bn.po
    fuel-web-bn.po
```

Use .po files in the locale folder instead of .pot.

**Comment by birajkarmakar** [comment]
Thanks Mathjazz,

Under bn-IN folder .po files are the same file of templates instead of .pot or .po file should be the blank. Not understood properly sorry!

**Comment by mathjazz** [comment]
The .po files should be the same as .pot. Just use different file extension (po instead of pot).

**Comment by birajkarmakar** [comment]
Thanks for clarify !
Done .
